import os
from typing import Optional

from groq import Groq
from mistralai.client import Mistral


GROQ_MODEL    = "groq/compound"
MISTRAL_MODEL = "devstral-latest"
VALID_LABELS = ("Anthropic", "Google", "Human", "Meta", "OpenAI")


def get_groq_client() -> Groq:
    key = os.getenv("GROQ_API_KEY")
    if not key:
        raise ValueError("GROQ_API_KEY not found in environment / .env")
    return Groq(api_key=key)


def get_mistral_client() -> Mistral:
    key = os.getenv("MISTRAL_API_KEY")
    if not key:
        raise ValueError("MISTRAL_API_KEY not found in environment / .env")
    return Mistral(api_key=key)


def ask_groq(prompt: str, client: Optional[Groq] = None, model: str = GROQ_MODEL) -> str:
    if client is None:
        client = get_groq_client()
    chat = client.chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        temperature=0,
        max_tokens=16,
    )
    return chat.choices[0].message.content


def ask_mistral(prompt: str, client: Optional[Mistral] = None, model: str = MISTRAL_MODEL) -> str:
    if client is None:
        client = get_mistral_client()
    chat = client.chat.complete(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        temperature=0,
        max_tokens=16,
    )
    return chat.choices[0].message.content


_SYSTEM_INTRO = (
    "You are an expert at identifying whether a short text was written by a human "
    "or generated by a specific AI model family. "
    "The only possible sources are:\n"
    "  - Human   : written by a real person\n"
    "  - OpenAI  : generated by a GPT model (OpenAI)\n"
    "  - Google  : generated by Gemini or Gemma (Google)\n"
    "  - Meta    : generated by Llama or similar (Meta)\n"
    "  - Anthropic: generated by Claude (Anthropic)\n\n"
    "Texts are short (~100-120 words)\n\n"
)


_FORMAT_INSTRUCTION = (
    "Reply with EXACTLY ONE word from the only possible sources.\n"
    "No explanation. No punctuation. Just the label."
)


def build_zero_shot_prompt(text: str) -> str:
    return (
        f"{_SYSTEM_INTRO}"
        f"{_FORMAT_INSTRUCTION}\n\n"
        f"Text: {text.strip()}\n"
        f"Label:"
    )


def build_few_shot_prompt(text: str, support_examples: list[dict]) -> str:
    examples_block = ""
    for ex in support_examples:
        examples_block += f"Text: {ex['Text'].strip()}\nLabel: {ex['Label']}\n\n"

    return (
        f"{_SYSTEM_INTRO}"
        "Here are some labeled examples to guide you:\n\n"
        f"{examples_block}"
        "------\n"
        "Now classify the following text using the same labels.\n"
        f"{_FORMAT_INSTRUCTION}\n\n"
        f"Text: {text.strip()}\n"
        f"Label:"
    )


def normalize_prediction(raw: Optional[str]) -> Optional[str]:
    if raw is None:
        return None

    text = raw.strip().rstrip(".")

    for label in VALID_LABELS:
        if text.lower() == label.lower():
            return label

    aliases = {
        "gpt":      "OpenAI",
        "chatgpt":  "OpenAI",
        "gemini":   "Google",
        "gemma":    "Google",
        "llama":    "Meta",
        "claude":   "Anthropic",
    }
    lower = text.lower()
    for alias, label in aliases.items():
        if alias in lower:
            return label

    for label in VALID_LABELS:
        if label.lower() in lower:
            return label

    return None
